export const products = [
  {
    title: 'Annapurna South',
    description: 'Get a better understanding of your traffic',
    map_url: 'https://goo.gl/maps/WVEfH9M162sM1Mrp6',
    start_date: '22-10-2021',
    end_date: '24-10-2021',
    location: 'Uttarkhand',
    img_name: 'annapurna-south.jpg',
  },
  {
    title: 'Gulmarg',
    description: 'Speak directly to your customers',
    map_url: 'https://goo.gl/maps/WVEfH9M162sM1Mrp6',
    start_date: '22-10-2021',
    end_date: '24-10-2021',
    location: 'Kashmir',
    img_name: 'gulmarg.jpeg',
  },
  {
    title: 'Virupaksha Temple',
    description: 'Your customers’ data will be safe and secure',
    map_url: 'https://goo.gl/maps/WVEfH9M162sM1Mrp6',
    start_date: '22-10-2021',
    end_date: '24-10-2021',
    location: 'Hampi',
    img_name: 'virupaksha-temple.jpg',
  },
  {
    title: 'Mullayanagiri',
    description: 'Connect with third-party tools',
    map_url: 'https://goo.gl/maps/WVEfH9M162sM1Mrp6',
    start_date: '22-10-2021',
    end_date: '24-10-2021',
    location: 'Chikmangaluru',
    img_name: 'mullayanagiri.jpg',
  },
  {
    title: 'Munnar',
    description: 'Build strategic funnels that will convert',
    map_url: 'https://goo.gl/maps/WVEfH9M162sM1Mrp6',
    start_date: '22-10-2021',
    end_date: '24-10-2021',
    location: 'Munnar',
    img_name: 'munnar.jpg',
  },
  {
    title: 'Tiger Hills',
    description: 'Build strategic funnels that will convert',
    map_url: 'https://goo.gl/maps/WVEfH9M162sM1Mrp6',
    start_date: '22-10-2021',
    end_date: '24-10-2021',
    location: 'Dargeeling',
    img_name: 'tiger-hills.png',
  },
]
